---
all:
  hosts:
    192.168.121.169:
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key

vars:
  ansible_user: vagrant
  ansible_ssh_private_key_file:  ~/.vagrant.d/insecure_private_key
  ansible_become: true
  ansible_become_method: sudo
