# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.vm.box = "generic/ubuntu2004"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :libvirt do |v|
    v.memory = 1024
    #v.linked_clone = true
  end

# Ubuntu Server
  config.vm.define "lamp" do |lamp|
    config.vm.box =  "generic/ubuntu2004"
    lamp.vm.hostname = "lamp.test"
  end
end
