# This is a comment for my inventory YML file
app:
  hosts:
    192.168.121.138
    192.168.121.217
db:
  hosts:
    192.168.121.123
multi:
  children:
    app:
    db:
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    ansible_become: true
    ansible_become_method: sudo
mygroup:
  children:
    db
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    ansible_become: true
    ansible_become_method: sudo
prod:
  children:
    db:
    app:
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    ansible_become: true
    ansible_become_method: sudo
