---
- hosts: multi # Defines hosts to which this is applied
  become: yes # Tell Ansible to use sudo

  tasks: # List tasks to run as part of this play
    -name: Install Apache. # This is for clarity, can be removed but add to logging and makes troubleshooting easier
    dnf: # We tell Ansible to use dnf module
      name:
        - httpd
        - httpd-devel
      state: present

      -name: Copy configuration files. # Again specify task for humans to read
      copy: # Module name
        src: "{{ item.src }}" # Reference variables
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
        with_items: # Define variables
          - src: httpd.conf
            dest: /etc/httpd/conf/httpd.conf
          - src: httpd-vhosts.conf
            dest: /etc/httpd/conf/httpd-vhosts.conf
            owner: root
            group: root
            mode: 0644

          - name: Make sure Apache is started now and at boot time.
            service: httpd
            status: started
            enabled: yes
